[pytest]

markers = tool_server_required: Test cases need built-in tool server support.
          model_api_required: Test cases need LLM model api provider.
          no_requirements: Test cases can run without any extra requirements.